<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Retrospective 59 minutes</title>
	<link rel="stylesheet" href="http://folk.ntnu.no/simeh/style.css">
	<!-- <link rel="shortcut icon" href="http://folk.ntnu.no/simeh/favicon.png" type="image/png" /> -->
	<!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
</head>

<body>

	<div id="main">

		<div id="title">
			<h1>Retrospective 59 Minutes</h1>
			<h2>Adventures in computer programming</h2>
		</div>

		<div id="pages">
			<a href="http://folk.ntnu.no/simeh/">top</a>
			 / 
			<a href="http://folk.ntnu.no/simeh/about">about</a>
			 / 
			<a href="http://folk.ntnu.no/simeh/projects" class="active_page">[projects]</a>
			 / 
			<a href="http://folk.ntnu.no/simeh/stuff">stuff</a>
			 / 
			<a href="http://folk.ntnu.no/simeh/blog">blog</a>
		</div>

		<div id="content">
		
		<p>Various projects and cool things I've worked on.</p>

<div class="project_preview">
<img src="./riemann/preview.png"></img>
<h1>Riemann Snake</h1>
<p>My first 3D game, written in C++ and OpenGL. You control a snake around a piece of spherical geometry, avoiding enemies and picking up apples. It has explosions and audio!</p>
<p>[<a href="./riemann/">Devlog</a>] [<a href="https://github.com/lightbits/riemannsnake">Source code</a>] [<a href="https://dl.dropboxusercontent.com/u/27844576/Releases/riemannsnake_windows.7z">Download (Windows)</a>]</p>
</div>

<div class="project_preview">
<img src="./planetgen/preview.png"></img>
<h1>Procedural Terrain Generator</h1>
<p>Creates mystical landscapes using noise functions, such as fractional Brownian motion (fBm) and variations of Perlin noise. A heightmap is generated by adding layers of noise with increasing frequency and decreasing amplitude.</p>
<p>[<a href="./planetgen/">Article</a>] [<a href="https://github.com/lightbits/glterrain">Source code</a>]</p>
</div>

<div class="project_preview">
<img src="./photons/preview.png"></img>
<h1>2D Photon Simulator</h1>
<p>A toy photon simulator that bounces a bunch of photons around in a 2D-collision-mapped image.</p>
<p>[<a href="./photons/">Article</a>] [<a href="https://github.com/lightbits/photons">Source code</a>]</p>
</div>

<div class="project_preview">
<img src="./raymarching/preview.png"></img>
<h1>Raymarching Distance Fields</h1>
<p>I implement a ray-casting based rendering technique, optimized using distance fields for ray acceleration. 
It runs in real-time with shading effects like soft-shadows, ambient occlusion and diffuse lighting.</p>
<p>[<a href="http://9bitscience.blogspot.no/2013/07/raymarching-distance-fields_14.html">Article</a>] [<a href="https://github.com/lightbits/ray-march">Source code</a>]
[<a href="https://dl.dropboxusercontent.com/u/27844576/raymarch/raymarching.html">WebGL demo</a>]
</p>
</div>

<div class="project_preview">
<img src="./atree/preview.png"></img>
<h1>HTML5 Christmas Tree</h1>
<p>A variation on the popular christmas tree, animated with HTML5 canvas and JS.</p>
<p>[<a href="./atree/">Demo</a>]</p>
</div>

<div class="project_preview">
<img src="./androidst2/preview.png"></img>
<h1>Android Plugin for Sublime Text 2</h1>
<p>A plugin for those who wish to make Android apps without heavy IDEs like Eclipse. 
The plugin provides an interface for creating new projects, as well as a single-step build- and install-system.</p>
<p>[<a href="http://dl.dropbox.com/u/27844576/Releases/st2android.zip">Download</a>] [<a href="https://github.com/lightbits/AndroidSt2">Source code</a>]</p>
</div>

<div class="project_preview">
<img src="./leveleditor/preview.jpg"></img>
<h1>C++ GUI Framework</h1>
<p>A graphical user interface based of callbacks and event-handling logic. It comes with a set of standard "controls",
such as textboxes and labels, which can be inherited and modified to fit whatever awesome application needs.</p>
<p>[<a href="https://github.com/lightbits/slgui">Source code</a>]</p>
</div>

<div class="project_preview">
<img src="./spriteassist/preview.png"></img>
<h1>Animation Assistant</h1>
<p>This application is meant to assist artists with tools that are often missing in regular painting programs. 
You can tile the sprite to see how it fits in a tilemap, and view it as an animation.</p>
<p>[<a href="http://dl.dropbox.com/u/27844576/Releases/spriteassist_1_0_1_0.zip">Download</a>]</p>
</div>

<div class="project_preview">
<img src="./colorpicker/preview.png"></img>
<h1>Color Picker</h1>
<p>A small tool for looking up color values. You can pick colors anywhere on the screen by pressing the 'pick' button,
which also responds to the enter key.</p>
<p>[<a href="http://dl.dropbox.com/u/27844576/Releases/colorpicker_1_5_1_0.zip">Download</a>] [<a href="https://github.com/lightbits/colors">Source code</a>]</p>
</div>

		</div>

	</div>
</body>
</html>